### ISSUE TITLE
Injected runs `injector.get` on a separate thread to endpoints themselves.

### ISSUE THREAD

**Issue by danielknell** [matyasrichter/fastapi-injector#4]
When you try and use a class that uses an event loop, this will fail currently as fastapi will offload the running of  function that provides the dependency onto a separate thread if they are defined as non-async functions. (this could also cause other "fun" shenanigans with threads...)

# Context

given the below example, the `root` method will run on the main thread using the event loop, but the `get_greeting` function runs on an entirely different thread instantiated by [anyio](https://pypi.org/project/anyio/).

```py
import fastapi

def get_greeting() -> str:
    return "Hello"

app = fastapi.FastAPI()

@app.get("/")
async def root(greeting: str = fastapi.Depends(get_greeting)):
    return {greeting: "World"}
```

this causes problems because the event loop belongs to the main thread, the one `root` runs on, so is now inaccessible to this new thread.

if you change the definition to the following, making it async, then both run on the same thread:

```py
async def get_greeting() -> str:
    return "Hello"
```

because `inject_into_route` defined [here](https://github.com/matyasrichter/fastapi-injector/blob/main/fastapi_injector/injected.py#L16) is a non-async function, it will always be run on a separate thread.

# Possible fixes

1. add the `async` keyword to `inject_into_route` and make it an async function, making all calls to `Injector` happen on the main thread.

2. add an `AsyncInjected` method that mirrors `Injected` but defines its own `inject_into_route` with the `async` keyword.

Happy to try and organise a PR for this if you have any preference on a solution?

# Minimal example

```py
import aiohttp
import fastapi
import fastapi_injector
import injector

app = fastapi.FastAPI()

@app.get("/")
async def root(aiohttp: aiohttp.ClientSession = fastapi_injector.Injected(aiohttp.ClientSession)):
    return {"Hello": "World"}

class MyModule(injector.Module):
    @injector.provider
    @injector.singleton
    def provide_session(self) -> aiohttp.ClientSession:
        return aiohttp.ClientSession()

container = injector.Injector([MyModule()])

fastapi_injector.attach_injector(app, container)
```

which results in the following logs when run:

```
$ uvicorn bug:app --reload --host 0.0.0.0 --port 8000
INFO:     Will watch for changes in these directories: ['/workspaces/connectors']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [59915] using StatReload
INFO:     Started server process [59920]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:37246 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 783, in get
    return self._context[key]
KeyError: <class 'aiohttp.client.ClientSession'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/venv/lib/python3.10/site-packages/fastapi/routing.py", line 225, in app
    solved_result = await solve_dependencies(
  File "/venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 535, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/venv/lib/python3.10/site-packages/fastapi_injector/injected.py", line 17, in inject_into_route
    return get_injector_instance(request.app).get(interface)
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
  File "/venv/lib/python3.10/site-packages/injector/__init__.py", line 1008, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/code/bug.py", line 19, in provide_session
    return aiohttp.ClientSession()
  File "/venv/lib/python3.10/site-packages/aiohttp/client.py", line 228, in __init__
    loop = get_running_loop(loop)
  File "/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 287, in get_running_loop
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.
INFO:     127.0.0.1:37250 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by matyasrichter** [comment]
Hi Daniel, thanks for the thorough description.
I would be happy to merge a PR with either of your proposed solutions. I'm more inclined towards the first one, turning the dependency constructed by `fastapi_injector` into a coroutine since providers are unlikely to perform any blocking IO. Maybe it would be worth considering an opposite approach - a `SyncInjected`, meant for injecting classes that require the provider to make blocking calls. What do you think?

**Comment by danielknell** [comment]
I would agree, it's generally considered bad practice to do busy work in injector providers, so making them coroutines shouldn't hurt things and will probably make it work more as folk expect. and i would agree a `SyncInjected` makes sense too for folk to explicitly opt into the sync handling.
